### ISSUE TITLE
TypeError: Cannot destructure property `activationValue` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by muhzulzidan** [TylerBarnes/using-gatsby-source-wordpress-experimental#9]
```⠹ Building development bundle
/usr/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot destructure property `activationValue` of 'undefined' or 'null'.
    at /home/za/Desktop/wpExperimental1/node_modules/gatsby-plugin-notifications/gatsby-node.js:47:16
    at /home/za/Desktop/wpExperimental1/node_modules/node-notifier/lib/utils.js:65:5
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)```

**Comment by muhzulzidan** [comment]
i fix it by deleting some lines on 
```
/home/za/Desktop/wpExperimental1/node_modules/gatsby-plugin-notifications/gatsby-node.js:47:16
    at /home/za/Desktop/wpExperimental1/node_modules/node-notifier/lib/utils.js:65:5````

**Comment by TylerBarnes** [comment]
Hi @muhzulzidan I've removed `gatsby-plugin-notifications` for now as a couple other linux users had issues with it too.
